@startuml seuence-diagram
!include <cloudinsight/mysql>
!include <tupadr3/font-awesome-5/chrome>
!include <tupadr3/font-awesome-5/vuejs>
' !include <tupadr3/dev2/redis>
!include <material/key>

title <b>用户没登录</b>

'https://github.com/rabelenda/cicon-plantuml-sprites/blob/master/sprites-list.md
'https://github.com/tupadr3/plantuml-icon-font-sprites
'https://github.com/Templarian/MaterialDesign

hide stereotype 
left to right direction
skinparam defaultTextAlignment center
' skinparam linetype ortho
skinparam rectangle {
  RoundCorner<<SIDE>> 25
  BorderStyle<<SIDE>> dotted
} 

actor USER

rectangle "CLIENT SIDE" <<SIDE>> {
  rectangle "<$chrome>\nBROWSER" as BROWSER
}
note right
  **COOKIES**

  <#80FF80>|= NAME |= VALUE |= EXPIRES |
  ' | SID | 1 | 2019-12-34 |
end note

rectangle "SERVER SIDE" <<SIDE>> {
  rectangle "<$vuejs>\nAPP" as APP
  rectangle "<$ma_key>\nSSO" as SSO
}


rectangle "DATABASE" <<SIDE>> {
  database "<$redis>\nREDIS" as REDIS
}
note right
  **SESSIONS**

  <#80FF80>|= KEY |= VALUE |
  ' | 1 | MaYun |
end note

rectangle "DATABASE" <<SIDE>> {
  database "<$mysql>\nMYSQL" as MYSQL
}
note right
  **USERS**

  <#80FF80>|= USERNAME |= PASSWORD |
  | MaYun | ALI |
  | MaHuaTeng | TENCENT |
  | RenZhengFei | HUAWEI |
end note

' USER -[hidden]-> BROWSER : 输入网址
' USER --> BROWSER : 输入用户名密码
' USER --> BROWSER : 输入用户名密码\nUSERNAME=MaYun\nPASSWORD=ABC
' USER -[hidden]-> BROWSER : 输入用户名密码\nUSERNAME=MaYun\nPASSWORD=ABC
' USER --> BROWSER : 输入用户名密码\nUSERNAME=MaYun\nPASSWORD=ALI
USER -[hidden]-> BROWSER : 输入用户名密码\nUSERNAME=MaYun\nPASSWORD=ALI

' BROWSER -[hidden]-> APP : COOKIE\nSID=1
' BROWSER --> APP : COOKIE\nSID=1
' BROWSER --> APP : **GET**
' BROWSER <-- APP : **302**\nREDIRECT\nTO SSO
' BROWSER <-[hidden]- APP : **302**\nREDIRECT\nTO SSO
' BROWSER --> APP : **GET**\nCODE=12
BROWSER -[hidden]-> APP : **GET**\nCODE=12

' BROWSER --> SSO : **GET**
' BROWSER <-[hidden]- SSO : **200**\n登录页面
' BROWSER <-- SSO : **200**\n登录页面
' BROWSER <-- SSO : ABC ≠ ALI\n**200**\n登录页面
' BROWSER <-[hidden]- SSO : ABC ≠ ALI\n**200**\n登录页面
' BROWSER <-- SSO : ALI = ALI\n**302**\nREDIRECT\nTO APP\nCODE=12
BROWSER <-[hidden]- SSO : ALI = ALI\n**302**\nREDIRECT\nTO APP\nCODE=12
' BROWSER --> SSO : **POST**\nUSERNAME=MaYun\nPASSWORD=ABC
' BROWSER -[hidden]-> SSO : **POST**\nUSERNAME=MaYun\nPASSWORD=ABC
' BROWSER --> SSO : **POST**\nUSERNAME=MaYun\nPASSWORD=ALI
' BROWSER -[hidden]-> SSO : **POST**\nUSERNAME=MaYun\nPASSWORD=ALI

APP -right---> SSO : **GET**\nCODE=12
' APP -[hidden]> SSO

' SSO --> MYSQL : **SELECT**\nUSERNAME=MaYun
' SSO -[hidden]-> MYSQL : **SELECT**\nUSERNAME=MaYun
' SSO <-- MYSQL : PASSWORD=ALI
SSO <-[hidden]- MYSQL : PASSWORD=ALI


APP -[hidden]-> REDIS : KEY=1

'hide USER
'hide BROWSER
'hide APP
' hide SSO

@enduml